TARGET = Blink
BOARD_TAG = atmega328

ARDUINO_LIBS =
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_DIR = /home/allen/Documents/Robotics/Arduino/arduino-0018/
ARDMK_DIR = /home/allen/Documents/Robotics/Arduino/arduino-0018/
AVR_TOOLS_DIR = /usr

include /home/allen/Documents/Robotics/Arduino/arduino-0018/Arduino.mk
